
function out = tf2latex(sys)
% TF2LATEX  converts tf model to LaTeX code
%   TEXT = TF2LATEX(SYS) converts the
%   tf model SYS to LaTeX text.
%   Dependencies: 
%     - toolboxes
%       - Control Systems
%       - Symbolic

syms s

num = sys.Numerator;
den = sys.Denominator;

out = latex(...
  poly2sym(...
    cell2mat(num),...
    s...
  )/...
  poly2sym(...
    cell2mat(den),...
    s...
  )...
);